name: gobrew
version: 25.03.06
summary: Count all packages built with a specific language
description: |
  Count all packages built with a specific programming language and distributed by Homebrew.
license: Apache-2.0

base: core24
confinement: strict
grade: stable
# platforms:
#   amd64:
#     build-on: [amd64]
#     build-for: [amd64]
#   arm64:
#     build-on: [amd64, arm64]
#     build-for: [arm64]
#   riscv64:
#     build-on: [amd64, arm64, riscv64]
#     build-for: [riscv64]


apps:
  gobrew:
    command: bin/gobrew
    plugs:
      - home
      - network

parts:
  gobrew:
    plugin: go
    build-snaps: [go/latest/stable]
    source: https://github.com/abanoubha/gobrew
    source-type: git
