name: gobrew
version: 24.08.24
summary: Count all packages built with a specific language
description: |
  Count all packages built with a specific programming language and distributed by Homebrew.
license: Apache-2.0

base: core24
confinement: devmode # change it to 'strict' later
grade: stable # change it to 'stable'

apps:
  gobrew:
    command: bin/gobrew
    plugs:
      - home
      - network

parts:
  gobrew:
    plugin: go
    build-snaps: [go/latest/stable]
    source: https://github.com/abanoubha/gobrew
    source-type: git
